[project]
name = "SteamPredictor"
version = "0.1.0"
description = "Machine learning to predict Steam metrics"
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "fastapi",
    "uvicorn",
    "catboost>=1.2.10",
    "dotenv>=0.9.9",
    "joblib",
    "minio>=7.2.20",
    "ollama>=0.6.1",
    "pandas>=3.0.0",
    "pillow>=12.1.0",
    "pyarrow>=23.0.1",
    "scikit-learn>=1.8.0",
    "sentence-transformers>=5.2.3",
    "torch",
    "torchvision",
    "xgboost>=3.2.0"
]

[dependency-groups]
not_in_container = [
    # Entrenamiento
    "tensorflow>=2.21.0",
    "optuna>=4.8.0",
    "wandb>=0.25.1",
    "scikeras>=0.13.0",
    "imblearn>=0.0",
    "statsmodels>=0.14.6",
    "umap-learn>=0.5.11",
    "hdbscan>=0.8.42",
    "fastopic>=1.0.1",

    # Análisis y visualización
    "matplotlib>=3.10.8",
    "seaborn>=0.13.2",
    "plotly>=6.5.2",
    "wordcloud>=1.9.6",
    "textblob>=0.19.0",
    "langdetect>=1.0.9",
    "nltk>=3.9.3",
    "spacy>=3.8.14",
    "unidecode>=1.4.0",

    # Extracción
    "beautifulsoup4>=4.14.3",
    "drissionpage>=4.1.1.2",
    "google-api-python-client>=2.189.0",
    "lxml>=6.0.2",
    "requests>=2.32.5",
    "stem>=1.8.2",

    # Otros
    "ipykernel>=7.2.0",
    "nbformat>=5.10.4",
    "tqdm>=4.67.3",
    "importlib>=1.0.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu118"
url = "https://download.pytorch.org/whl/cu118"
explicit = true

[tool.uv.workspace]
members = ["app"]


[tool.uv.sources]
torch = [
  { index = "pytorch-cpu", marker = "sys_platform != 'linux' and sys_platform != 'win32'" },
  { index = "pytorch-cu118", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
  { index = "pytorch-cpu", marker = "sys_platform != 'linux' and sys_platform != 'win32'" },
  { index = "pytorch-cu118", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]

[tool.uv]
default-groups = ["not_in_container"]